### ISSUE TITLE
DllNotFoundException on .Net 6

### ISSUE THREAD

**Issue by AndreyFromGomel** [mono/opentk#31]
Hi, I tried to migrate project to .Net 6, I replaced Assembly reference to Xamarin.Legacy.OpenTK package, but now app crashes at runtime with DllNotFoundException:
```
android.runtime.JavaProxyThrowable: System.DllNotFoundException: libGLESv2.dll
    at OpenTK.Graphics.ES20.GL.GetInteger(GetPName pname, Int32* params) in OpenTK-1.0.dll
```
Looks like package does not contain all necessary assemblies.

**Comment by AndreyFromGomel** [comment]
[OpenTK.zip](https://github.com/mono/opentk/files/7098748/OpenTK.zip)
Attached sample to reproduce - Xamarin.Android sample works, .Net 6 fails at runtime.

@dellis1972 sorry to bother you, you created NuGet package so may be you can help resolve this issue.

**Comment by dellis1972** [comment]
`libGLESv2` should be provided by the android system not shipped with the nuget. That suggests that something is not right in the way .net 6 is searching for native libraries.  I'll take a look when I'm back of holiday.

**Comment by AndreyFromGomel** [comment]
Thank you, have a nice holiday.

Btw, it looks like not only libGLESv2 is missing:
![image](https://user-images.githubusercontent.com/46677631/131984558-dfbd07c5-0107-4aeb-a202-0feeebc5535d.png)

**Comment by dellis1972** [comment]
@AndreyFromGomel as I mentioned all those native libraries should be provided by the Operating system not shipped with the package. I suspect it needs a `OpenTK.deps.json` file for .net 6 to work correctly.

**Comment by AndreyFromGomel** [comment]
Hi, checked new package and now it works well. Thank you.
